Improve error reporting when procedural macros are misused. (#6)
Improve error reporting when procedural macros are misused.

Using the span information will make is so that the precise location of the
error is underlined.

An example error when an incorrect number of arguments are supplied
```
error: Incorrect number of function arguments, the expected arguments are (ctx: &impl HasReceiveContext, amount: Amount, state: &mut MyState)
   --> src/lib.rs:140:5
    |
140 | /     _ctx: &impl HasReceiveContext,
141 | |     _state: &mut State,
    | |_______________________^

error: aborting due to previous error
```